version: '3.8'

services:
  app:
    build: .
    ports:
      - "3007:3007"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
    environment:
      - NODE_ENV=development
      - PORT=3007
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3007/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  node_modules:
  dist: 